### ISSUE TITLE
Make fire graph resize dynamically

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#300] opened 2017-05-09 17:48 UTC
STR:

- make browser window small, open Fire map, open the Large Fire Seasons graphs
- resize your browser window to be bigger

Expected: graph resizes to take up available space
Actual: it doesn't.

This works the other way too.  It looks like we need something to listen for window resize events then fire a resize on the plot.  [This reference](https://plot.ly/javascript/responsive-fluid-layout/) may be useful.

**Comment by cstephen** [comment] 2017-05-09 18:00
This issue is a duplicate of #298. I'll close #298 because this one has a better description.

**Comment by cstephen** [comment] 2017-05-11 20:45
This has been fixed with #312.

**Closed by cstephen** 2017-05-11 20:45 UTC
Labels: bug, Fire map, ready
